_wdt:
    resource: '@WebProfilerBundle/Resource/config/routing/wdt.xml'
    prefix: /_wdt

_profiler:
    resource: '@WebProfilerBundle/Resource/config/routing/profiler.xml'
    prefix: /_profiler

_errors:
    resource: '@TwigBundle/Resource/config/routing/errors.xml'
    prefix: /_error

_main:
    resource: routing.yml
