<?php

namespace Grt\ResBundle\Entity\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{

    private $fieldSorting = array('name','fields');

    /**
     * @return array
     */
    public function getAllBases($field = 'name',$order = 'ASC',$currentPage = 1, $limit = 5)
    {
        if (in_array($field, $this->fieldSorting)) {
            $field = 'b.' . $field;
            $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->addOrderBy($field, $order);

            $paginator = new Paginator($qb);

            $paginator->getQuery()
                ->setFirstResult($limit * ($currentPage - 1))// Offset
                ->setMaxResults($limit); // Limit

            return $paginator;
        }
        return null;
    }



}
