<?php

namespace Grt\ResBundle\Entity\Repository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFindUserBase($baseId, $userId)
    {
        $db = $this->createQueryBuilder('r')
            ->select('r')
            ->andWhere('r.base_id =:baseId ')
            ->andWhere('r.user_id=:userId')
            ->setParameter(':baseId',$baseId)
            ->setParameter(':userId',$userId);

        $res = $db->getQuery()->getResult();
        return $db->getQuery()->getResult();
    }
}
